### ISSUE TITLE
Received unknown json

### ISSUE THREAD

**Issue by Dawnnnnnn** [czp3009/bilibili-lottery-listener#1]
2018-05-23 09:51:01.797 ERROR 116546 --- [tLoopGroup-6-25] c.h.b.a.l.s.handler.LiveClientHandler    : Received unknown json below: 
{
  "cmd": "ROOM_RANK",
  "data": {
    "roomid": 3882711,
    "rank_desc":"小时榜"
    "color": "#FB7299",
    "h5_url": "https://live.bilibili.com/p/eden/rank-h5-current?anchor_uid\u003d96619967",
    "timestamp": 1527083461
  }
}

**Comment by Dawnnnnnn** [comment]
"rank_desc":"小时榜"

**Comment by czp3009** [comment]
待我有空再增加这个数据包

**Comment by czp3009** [comment]
已添加此数据包 https://github.com/czp3009/bilibili-api/commit/ad2aabb7fb69c7e4bec3308dac39cdc1b50d81f1
