### ISSUE TITLE
这个报错是为啥啊

### ISSUE THREAD

**Issue by lovezm** [czp3009/bilibili-lottery-listener#10]
请教一下大佬
![image](https://user-images.githubusercontent.com/10624938/45005703-94b67a00-b027-11e8-88d3-544cfda1587e.png)

**Comment by lovezm** [comment]
我这显示推送了...但是客户端连上去看不到...

**Comment by lovezm** [comment]
还望大佬写个栗子-,-

**Comment by lovezm** [comment]
还是说只能使用STOMP

**Comment by lovezm** [comment]
希望能出个栗子-，-

**Comment by czp3009** [comment]
这个不是报错，是正常日志。

如何订阅的案例在readme中，暂时只有js的。

协议是基于 Web socket 的 stomp

**Comment by lovezm** [comment]
好吧 - - 我看控制塔他就链接成功了 啥都没打印 我以为是报错

**Comment by czp3009** [comment]
这些抽奖事件不是什么时候都有的，是看脸的
