### ISSUE TITLE
问个问题，这个抽奖好一点情况能抽到啥？

### ISSUE THREAD

**Issue by gMan1990** [czp3009/bilibili-lottery-listener#11]
我看都是辣条么~

**Comment by czp3009** [comment]
这是 B站 决定的, 通常都是 辣条.

B站 也是要赚钱的, 主播能拿到钱的礼物, 都必须是花钱买的. 辣条这种礼物主播收不到钱. 所以辣条可以随便送. 如果送辣条给主播,
主播可以收到钱的话, B站 就是下一个拼多多.

c828a0d973c37d2a <notifications@github.com> 于2019年1月22日周二 下午3:42写道：

**Comment by gMan1990** [comment]
不过我有看到什么银瓜子，小电视抱枕。。。（我准备用下你这个项目，先精神上支持你的不懈开发
下一个拼多多？拼多多能薅吗？

**Comment by czp3009** [comment]
小电视抱枕那个是实物奖品. 根据我的调查, 实物奖品除非是冲过钱的账户, 不然是抽不到的. 换而言之, 无氪账户只能抽一些没什么用的东西.

(拼多多不是被撸爆了么

(我是老实人

**Comment by gMan1990** [comment]
```除非是冲过钱的账户, 不然是抽不到的```看到你说的，心里凉了一下。。。（我只氪过￥20左右
拼多多后面不是说回收了吗。已用掉的应该赚到了吧。（我看到都已经车尾气都没了

**Comment by czp3009** [comment]
你连大会员都没有, 你也好意思说自己是二次元(暴论

c828a0d973c37d2a <notifications@github.com> 于2019年1月24日周四 上午11:22写道：
