### ISSUE TITLE
SPECIAL_GIFT_END_EVENT Repeated information

### ISSUE THREAD

**Issue by Dawnnnnnn** [czp3009/bilibili-lottery-listener#2]
![image](https://user-images.githubusercontent.com/24506421/40465030-2d49c308-5f51-11e8-9d70-4f8eabbc9184.png)

**Comment by czp3009** [comment]
待我有空写个Python范例

**Comment by czp3009** [comment]
我找了半天, 没找到 python 里用的 stomp over websocket 的库.

弃坑.svg

**Comment by Dawnnnnnn** [comment]
救救孩子.jpg

**Comment by czp3009** [comment]
救不动.bmp

**Comment by czp3009** [comment]
我决定了, 没有 python 范例
